services:

  # server:
  #   build:
  #     context: .
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000

  logging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: logging
    ports:
      - "3002:3002"
    env_file:
      - .docker.env
    environment:
      PORT: ${LOGGING_SERVICE_PORT}
      RIDER_SERVICE_HOST: ${RIDER_SERVICE_HOST}
      RIDER_SERVICE_PORT: ${RIDER_SERVICE_PORT}
      MONGO_DATABASE_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/uber_services?authSource=admin
    command: sh -c "node dist/apps/logging/main"
    depends_on:
      - rider
      - mongo
    restart: unless-stopped

  rider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: rider
    expose:
      - "3001"
    env_file:
      - .docker.env
    environment:
      RIDER_SERVICE_PORT: ${RIDER_SERVICE_PORT}
    command: sh -c "node dist/apps/rider/main"
    restart: unless-stopped

  uber:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: uber
    expose:
      - "3000"
    env_file:
      - .docker.env
    environment:
      UBER_SERVICE_PORT: ${UBER_SERVICE_PORT}
    command: sh -c "node dist/apps/uber-services/main"
    restart: unless-stopped
# 
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo

volumes:
  mongo_data:
